"""The captured vintages, and the four properties that make them worth capturing.

WHAT IS COMMITTED. Not the versions: four series across their full publication history is about
535 documents and 200,000 observations, most of which repeat the document before them. What is
committed is one row each time a period's value changed, which is the bitemporal table itself
rather than a compression of it.

SOURCE.json IS RECOMPUTED HERE RATHER THAN TRUSTED. It is written by the capture script and
carries the counts this repository quotes, so it is exactly the kind of file that goes stale the
first time somebody re-runs the capture and forgets to look. Every figure in it is derived again
from the CSVs.

THE FOUR PROPERTIES ARE NOT INCIDENTAL. Each one is a way a bitemporal warehouse gets built
wrong, and this data contains all four, which is why these four series were chosen.
"""

from __future__ import annotations

import csv
import json
import pathlib
from collections import defaultdict
from itertools import pairwise
from typing import Any

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
DATA = REPO / "src" / "quarryz" / "data" / "vintages"
COLUMNS = ["period", "value", "released", "version"]
WITHDRAWN = "WITHDRAWN"


def source() -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads((DATA / "SOURCE.json").read_text(encoding="utf-8"))
    return loaded


def series_names() -> list[str]:
    return [str(entry["cdid"]) for entry in source()["series"]]


def rows(cdid: str) -> list[dict[str, str]]:
    with (DATA / f"{cdid}.csv").open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def described(cdid: str) -> dict[str, Any]:
    found: dict[str, Any] = next(entry for entry in source()["series"] if entry["cdid"] == cdid)
    return found


@pytest.mark.parametrize("cdid", series_names())
def test_every_series_has_the_columns_the_loader_expects(cdid: str) -> None:
    """A shifted column puts a release date where a value belongs and nothing reports it."""
    captured = rows(cdid)
    assert captured, f"{cdid}.csv has no rows"
    assert list(captured[0]) == COLUMNS


@pytest.mark.parametrize("cdid", series_names())
def test_the_recorded_counts_are_the_ones_in_the_files(cdid: str) -> None:
    """SOURCE.json is regenerated by the capture, so it is recomputed rather than believed.

    IT SAID THAT BEFORE AND IT WAS TRUE OF FIVE FIELDS OF TWELVE. `versions` in particular, one
    of the numbers this repository quotes and the direct output of the walk-to-404 argument,
    was derived from nothing and could have been set to 9999 with a green suite. A docstring
    promising verification is exactly the assurance that stops a reviewer verifying.
    """
    captured = rows(cdid)
    entry = described(cdid)
    assert entry["changes"] == len(captured)
    assert entry["distinct_release_dates"] == len({row["released"] for row in captured})
    assert entry["withdrawn_rows"] == sum(1 for row in captured if row["value"] == WITHDRAWN)
    assert entry["first_release"] == min(row["released"] for row in captured)
    assert entry["last_release"] == max(row["released"] for row in captured)

    # The version count, bounded by the labels the corpus carries. The CSV holds a row only
    # where a value changed, so a version that published nothing new leaves no label behind and
    # the highest numbered label is a LOWER bound on the walk. Plus one for `current`, which is
    # not numbered. An exact equality would be wrong here and a bound is the honest check.
    numbered = [int(row["version"][1:]) for row in captured if row["version"].startswith("v")]
    assert numbered, f"{cdid} carries no numbered version labels at all"
    assert entry["versions"] >= max(numbered) + 1, (
        f"{cdid} records {entry['versions']} versions and its corpus contains v{max(numbered)}, "
        f"so the recorded count is lower than the labels it holds"
    )
    assert entry["versions"] <= max(numbered) + 5, (
        f"{cdid} records {entry['versions']} versions against a highest label of "
        f"v{max(numbered)}. More than a handful of trailing versions that changed nothing is "
        f"possible and is worth a look rather than a pass"
    )

    # THE FIELD THE WHOLE TIE-BREAK ARGUMENT RESTS ON, and it was recomputed by nothing. Every
    # claim this repository makes about ordering by (released, version) rather than by the date
    # alone depends on there being release dates that carry two versions. If that list were
    # wrong, or stale, the argument would read as strongly as ever and be about nothing.
    # A SUBSET, NOT AN EQUALITY, and getting that wrong is what taught me what the field means.
    # It is computed at capture time over the VERSION WALK: every date on which the publisher
    # issued two versions. The CSV holds a row only where a value changed, so it can only
    # witness a date where BOTH versions changed something. Measured across the four series:
    # DZLS 6 dates walked and 3 witnessed, IKBJ 15 and 2, KAC3 4 and 4, MGRZ 3 and 3. The gap
    # is 18 versions that were published and changed no number at all.
    #
    # The subset direction is the one that can catch a stale file: a date the corpus witnesses
    # and the walk never recorded would mean SOURCE.json describes a different capture.
    versions_per_date: dict[str, set[str]] = defaultdict(set)
    for row in captured:
        versions_per_date[row["released"]].add(row["version"])
    witnessed = sorted(date for date, seen in versions_per_date.items() if len(seen) > 1)
    walked = entry["release_dates_shared_by_two_versions"]
    assert set(witnessed) <= set(walked), (
        f"{cdid} has release dates carrying two versions in the CSV that SOURCE.json does not "
        f"record at all: {sorted(set(witnessed) - set(walked))}. The recorded file describes a "
        f"different capture from the one committed beside it"
    )
    assert walked == sorted(walked), f"{cdid} records the shared dates out of order"
    assert len(set(walked)) == len(walked), f"{cdid} records a shared date twice"

    # `title` is editorial and cannot be recomputed from a CSV of numbers, so it is named here
    # as the one field this test does not stand behind. `why` USED TO BE NAMED BESIDE IT AND WAS
    # NOT EDITORIAL: three of the four stated a count, and two of those counts were wrong. The
    # figures moved into `why_numbers`, which the test below recomputes, and what is left in
    # `why` is held to prose.
    assert entry["title"].strip()
    assert entry["why"].strip()
    assert entry["distinct_titles_over_time"], f"{cdid} records no title at all"
    assert entry["url"].endswith("/data")
    assert cdid.lower() in entry["url"]


@pytest.mark.parametrize("cdid", series_names())
def test_the_figures_inside_why_are_recomputed_from_the_rows(cdid: str) -> None:
    """THE FIELD A COMMENT USED TO EXCUSE AS UNVERIFIABLE, AND TWO OF ITS NUMBERS WERE WRONG.

    `why` said DZLS annual 2020 had "seventeen distinct value states ... the clearest case in
    the set". That period carries forty-five states, and it is not the clearest case: 2016 Q2
    carries fifty-four. It said KAC3's March 2010 had "read 4.3, 2.9, 4.9 and 5.0", and the
    corpus also carries 2.8, published 2020-02-18. MGRZ's "revised in 249 of 941 periods"
    recomputes exactly, which is the tell: one of the three was derived and two were typed.

    The sentence was the source of truth in `scripts/capture_vintages.py`, so re-running the
    capture could not have corrected it. Every figure now comes from the rows the capture just
    wrote, and it is recomputed here from the committed CSV rather than from that function,
    because checking a computation with the same computation checks nothing.
    """
    captured = rows(cdid)
    numbers = described(cdid)["why_numbers"]

    states: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for row in captured:
        states[row["period"]].append((row["released"], row["value"]))

    assert numbers["periods"] == len(states)
    assert numbers["periods_revised"] == sum(1 for seq in states.values() if len(seq) > 1)

    ranked = sorted(
        ((len({value for _, value in seq}), period) for period, seq in states.items()),
        key=lambda pair: (-pair[0], pair[1]),
    )
    assert (numbers["most_restated_period_states"], numbers["most_restated_period"]) == ranked[0], (
        f"{cdid} records {numbers['most_restated_period']} at "
        f"{numbers['most_restated_period_states']} states and the corpus makes it {ranked[0]}"
    )

    biggest, moved = 0, ("", "", "", "")
    for period, sequence in states.items():
        for (_, was), (released, now) in pairwise(sequence):
            if WITHDRAWN in (was, now):
                continue
            size = abs(int(float(now)) - int(float(was)))
            if size > biggest:
                biggest, moved = size, (period, was, now, released)
    recorded = numbers["largest_revision"]
    assert (
        recorded["period"],
        recorded["was"],
        recorded["now"],
        recorded["released"],
        recorded["size"],
    ) == (*moved, biggest), f"{cdid} records {recorded} and the corpus gives {moved} at {biggest}"


@pytest.mark.parametrize("cdid", series_names())
def test_why_states_no_figure_a_csv_could_settle(cdid: str) -> None:
    """The contract that keeps the split honest, rather than a comment saying it is honest.

    `why` is the one field nothing recomputes, so the smaller it is the less rides on trust.
    A digit in it is a figure somebody typed, and this repository has already been caught twice
    by exactly that: the number goes in `why_numbers`, where a recapture rewrites it.
    """
    why = described(cdid)["why"]
    assert not any(character.isdigit() for character in why), (
        f"{cdid} states a figure in `why`, which nothing recomputes: {why!r}. Numbers belong in "
        f"`why_numbers`, which the capture derives from the rows it just wrote"
    )


def test_a_release_date_is_not_a_unique_key() -> None:
    """TRAP ONE, and the reason transaction time here is a pair rather than a date.

    Two versions published on the same day are two different states of the world. A warehouse
    keyed on the release date alone merges them, and the merge is silent because the second one
    simply overwrites the first.
    """
    # TWO DIFFERENT POPULATIONS, AND THIS TEST FIRST ASSERTED THEY WERE EQUAL. SOURCE.json
    # counts dates shared by two VERSIONS, taken from the walk. The CSV holds a row only where a
    # value CHANGED, so a version that published nothing new leaves no trace in it and its
    # release date can be missing entirely. The right relation is containment, and the claim
    # that matters is that the trap is visible in the committed data at all, not only in the
    # metadata beside it.
    declared: dict[str, list[str]] = {}
    visible: dict[str, list[str]] = {}
    for cdid in series_names():
        by_date: dict[str, set[str]] = defaultdict(set)
        for row in rows(cdid):
            by_date[row["released"]].add(row["version"])
        visible[cdid] = sorted(date for date, versions in by_date.items() if len(versions) > 1)
        declared[cdid] = list(described(cdid)["release_dates_shared_by_two_versions"])
        assert set(visible[cdid]) <= set(declared[cdid]), (
            f"{cdid} shows a shared release date in the data that the capture did not record: "
            f"{sorted(set(visible[cdid]) - set(declared[cdid]))}"
        )

    assert sum(len(dates) for dates in declared.values()) > 0, (
        "no release date in this corpus is shared by two versions, so the pair key this "
        "repository argues for is not motivated by its own data. Find a series where it is, or "
        "drop the claim"
    )
    assert sum(len(dates) for dates in visible.values()) > 0, (
        f"the shared dates exist only in SOURCE.json and never in the committed rows, so a "
        f"reader cannot see the trap in the data: {declared}"
    )


def test_the_pair_of_date_and_version_is_unique() -> None:
    """The other half of trap one: the key this repository does use has to actually be a key."""
    for cdid in series_names():
        seen: set[tuple[str, str, str]] = set()
        for row in rows(cdid):
            key = (row["period"], row["released"], row["version"])
            assert key not in seen, f"{cdid} records {key} twice"
            seen.add(key)


def test_every_version_label_is_well_formed_and_carries_one_release_date() -> None:
    """Added because a mutation renaming a version to v999 passed every other test here.

    The version label is half the transaction-time key, so nothing validating it means half the
    key is unchecked. Three invariants, each of which a corrupted capture would break: the label
    is `v<number>` or `current`, one label never carries two release dates, and the version
    numbering agrees with the publication order.

    The last one is not decoration. If v107 could carry a date before v106's, then "the version
    after this one" and "the version published after this one" would be different orderings, and
    every as-of query would have to say which it meant.
    """
    import re

    for cdid in series_names():
        dates: dict[str, set[str]] = defaultdict(set)
        for row in rows(cdid):
            assert re.fullmatch(r"v\d+|current", row["version"]), (
                f"{cdid} carries a version label of {row['version']!r}"
            )
            dates[row["version"]].add(row["released"])

        for label, released in dates.items():
            assert len(released) == 1, f"{cdid} {label} carries {sorted(released)}"

        numbered = sorted(
            (int(label[1:]), next(iter(released)))
            for label, released in dates.items()
            if label != "current"
        )
        for (earlier, when), (later, then) in pairwise(numbered):
            assert when <= then, (
                f"{cdid} v{earlier} was published {when} and v{later} was published {then}, so "
                f"the version order and the publication order disagree"
            )


def test_a_withdrawn_value_is_kept_as_a_withdrawal() -> None:
    """TRAP THREE. An emptied value is not a null and not an absence.

    The publisher keeps the period and empties the number, so a loader mapping the empty string
    to NULL cannot tell "not published yet" from "withdrawn after publication". Both exist here.
    """
    withdrawn = {cdid: described(cdid)["withdrawn_rows"] for cdid in series_names()}
    assert sum(withdrawn.values()) > 0, (
        f"no series here has a withdrawn value, so trap three is not demonstrated: {withdrawn}"
    )

    # And a withdrawal must be followed by something, or it is indistinguishable from the series
    # simply ending, which is a different event.
    restored = 0
    for cdid in series_names():
        by_period: dict[str, list[str]] = defaultdict(list)
        for row in rows(cdid):
            by_period[row["period"]].append(row["value"])
        for values in by_period.values():
            for earlier, later in pairwise(values):
                if earlier == WITHDRAWN and later != WITHDRAWN:
                    restored += 1
    assert restored > 0, (
        "every withdrawal here is terminal, so nothing distinguishes a withdrawal from the end "
        "of the series and the interesting case is not in the corpus"
    )


def test_a_series_title_changes_without_the_numbers_being_rebased() -> None:
    """TRAP FOUR's cousin, and the one a sibling repository was caught by.

    There, a series was rebased and the title went on claiming the old base for three years. Here
    the opposite happens: titles change while the numbers do not move as a block. A warehouse
    that keys on the title, or that treats a title change as a break in the series, is wrong
    both times.
    """
    changed = {cdid: described(cdid)["distinct_titles_over_time"] for cdid in series_names()}
    assert any(len(titles) > 1 for titles in changed.values()), (
        f"no series here was ever renamed, so this claim has no evidence: {changed}"
    )

    # AND THE SECOND HALF OF THE NAME, which used to be enforced nowhere. This test read one
    # metadata field and asserted nothing about a number, while its own name promises the
    # numbers were not rebased and its docstring cites a sibling repository caught by exactly
    # that. The property is computable from the committed corpus, so it is computed.
    #
    # A rebasing multiplies a whole series by one constant, so the ratio between consecutive
    # vintages is the same for every period. Reconstructed by forward-filling the change table,
    # the median ratio between each pair of consecutive vintages must be exactly 1.
    for cdid in ("KAC3", "MGRZ"):
        vintages: dict[str, dict[str, float]] = {}
        running: dict[str, float] = {}
        for row in sorted(rows(cdid), key=lambda entry: (entry["released"], entry["version"])):
            if row["value"] != WITHDRAWN:
                running[row["period"]] = float(row["value"])
            vintages[f"{row['released']}/{row['version']}"] = dict(running)

        ordered = [vintages[key] for key in sorted(vintages)]
        assert len(ordered) > 50, f"{cdid} reconstructs only {len(ordered)} vintages"
        for earlier, later in pairwise(ordered):
            shared = [
                later[period] / earlier[period]
                for period in earlier
                if period in later and earlier[period] != 0
            ]
            if len(shared) < 10:
                continue
            shared.sort()
            median = shared[len(shared) // 2]
            assert median == 1.0, (
                f"{cdid} has a pair of consecutive vintages whose median ratio is {median}, "
                f"which is what a rebasing looks like. A rescaling read as a revision is the "
                f"trap these four series were chosen to avoid"
            )


def test_the_headline_revision_is_the_largest_in_the_corpus() -> None:
    """THE MAXIMALITY HALF, WHICH WAS ASSERTED IN AN ERROR MESSAGE AND CHECKED BY NOTHING.

    "The largest single revision found anywhere in these four" appears in SOURCE.json, in the
    capture script and in the ledger, and the only test defending it re-checked the arithmetic
    of one hard-coded pair. It could fail if that pair changed and could never fail if some
    other pair became larger, which is the direction that matters: the corpus is regenerated
    against a live publisher, and the next release revising a DZLS or IKBJ annual by more than
    24,521 would make the claim false with a green suite.

    So every adjacent change in every series is measured. Only numeric states count: a
    withdrawal is a revision of a different kind and subtracting it from a number is meaningless.
    """
    largest = (0, "", "", "")
    for cdid in series_names():
        states: dict[str, list[tuple[str, str]]] = defaultdict(list)
        for row in rows(cdid):
            states[row["period"]].append((row["released"], row["value"]))
        for period, sequence in states.items():
            for (_, before), (when, after) in pairwise(sequence):
                if before == WITHDRAWN or after == WITHDRAWN:
                    continue
                size = abs(int(float(after)) - int(float(before)))
                if size > largest[0]:
                    largest = (size, cdid, period, when)

    size, cdid, period, when = largest
    assert (cdid, period) == ("IKBJ", "2021"), (
        f"the largest single revision in this corpus is now {cdid} {period}, {size} at {when}, "
        f"and three files still say it is IKBJ 2021 at 24,521"
    )
    assert size == 24521, f"the largest revision is {size}, and the quoted figure is 24,521"
    assert when == "2023-10-11"

    # AND THE SUPERLATIVE ITSELF, joined to what each series recorded. IKBJ's `why` says it
    # carries the largest single revision found anywhere in these four, which is a claim about
    # the other three and was checked against none of them.
    per_series = {
        name: described(name)["why_numbers"]["largest_revision"] for name in series_names()
    }
    winner = max(per_series, key=lambda name: int(per_series[name]["size"]))
    assert (winner, per_series[winner]["size"]) == (cdid, size), (
        f"{winner} records the largest revision in this corpus at {per_series[winner]['size']}, "
        f"and {cdid} is the series whose entry claims it"
    )


def test_the_headline_revision_is_in_the_data_with_the_numbers_the_readme_quotes() -> None:
    """The one figure a reader will check, recomputed from the file rather than remembered."""
    annual_2021 = [row for row in rows("IKBJ") if row["period"] == "2021"]
    states = [(row["released"], row["value"]) for row in annual_2021]
    assert ("2023-01-13", "-28039") in states
    assert ("2023-10-11", "-3518") in states

    before = next(value for released, value in states if released == "2023-01-13")
    after = next(value for released, value in states if released == "2023-10-11")
    assert int(after) - int(before) == 24521, (
        f"the largest single revision in this corpus is not {int(after) - int(before)}"
    )


def test_the_licence_and_its_attribution_are_recorded_beside_the_data() -> None:
    """The OGL requires a specific sentence, and a licence named without it is not honoured."""
    licence = source()
    assert licence["licence"] == "Open Government Licence v3.0"
    assert licence["attribution"] == (
        "Contains public sector information licensed under the Open Government Licence v3.0."
    )
    assert "adapt the Information" in licence["permits_adaptation"]


def test_none_of_these_series_belongs_to_the_sibling_that_also_reads_ons() -> None:
    """Two repositories in one portfolio reading the same four series would be one repository.

    Named here rather than remembered, because the overlap is invisible from inside either one.
    """
    theirs = {"IHYQ", "MGSX", "ABMI", "D7BT"}
    assert not theirs & set(series_names())


def _capture_vintages() -> Any:
    import sys

    sys.path.insert(0, str(REPO / "scripts"))
    import capture_vintages

    return capture_vintages


def test_a_single_series_capture_merges_into_the_existing_file_instead_of_replacing_it() -> None:
    """The documented `capture_vintages.py IKBJ` form used to write `"series": captured` with
    `captured` holding only IKBJ, so the other three entries were deleted from SOURCE.json even
    though their CSVs stayed on disk untouched. `merge_series` is the fix, exercised here with
    fabricated entries standing in for a real, network-fetched capture: it must carry every
    series `merge_series` was not asked to update straight through, unchanged, and take the new
    value only for the one that was.
    """
    capture_vintages = _capture_vintages()
    existing = [{"cdid": cdid, "marker": "old"} for cdid in sorted(capture_vintages.SERIES)]
    captured = [{"cdid": "IKBJ", "marker": "new"}]

    merged = capture_vintages.merge_series(existing, captured)

    assert {entry["cdid"] for entry in merged} == set(capture_vintages.SERIES)
    by_cdid = {entry["cdid"]: entry for entry in merged}
    assert by_cdid["IKBJ"]["marker"] == "new", "the series just captured was not updated"
    for cdid in capture_vintages.SERIES:
        if cdid != "IKBJ":
            assert by_cdid[cdid]["marker"] == "old", (
                f"{cdid} was not requested this run and should have been carried over "
                f"unchanged, not replaced or dropped"
            )


def test_the_docstrings_withdrawal_example_matches_the_corpus() -> None:
    """`capture_vintages.py`'s worked example for trap three used to say IKBJ's April 1997 read
    empty "for four publications" between 196 and 257. The corpus holds thirty eight, v18 to
    v55, spanning two and a half years. Recomputed here from the committed CSV, not from the
    docstring, so a future edit that retypes another wrong count is caught the same way this one
    should have been.
    """
    capture_vintages = _capture_vintages()
    history = sorted(
        (row["released"], row["version"], row["value"])
        for row in rows("IKBJ")
        if row["period"] == "1997 APR"
    )
    assert history[0][1:] == ("v6", "196")
    withdrawal = next(entry for entry in history if entry[2] == WITHDRAWN)
    restoration = next(
        entry for entry in history if entry[0] > withdrawal[0] and entry[2] != WITHDRAWN
    )
    assert (withdrawal[0], withdrawal[1]) == ("2017-04-06", "v18")
    assert (restoration[0], restoration[1], restoration[2]) == ("2019-10-09", "v56", "257")

    span = int(restoration[1][1:]) - int(withdrawal[1][1:])
    assert span == 38, f"the withdrawal now spans {span} versions, and the docstring must say so"

    docstring = capture_vintages.__doc__ or ""
    assert "four publications" not in docstring, (
        "the docstring's worked example understates the withdrawal span again; it held empty "
        "for 38 versions (v18 to v55), not four"
    )


def test_merge_series_refuses_a_write_that_would_lose_a_series_entirely() -> None:
    """The other half of the guard: a first capture has to be a full one.

    If a series has no entry in the existing file and this run did not capture it either, there
    is nothing to carry forward, and writing the file anyway would silently drop it from
    SOURCE.json for good.
    """
    capture_vintages = _capture_vintages()
    existing = [{"cdid": "IKBJ", "marker": "old"}]
    captured = [{"cdid": "DZLS", "marker": "new"}]

    with pytest.raises(SystemExit):
        capture_vintages.merge_series(existing, captured)
