"""The captured vintages, and the four properties that make them worth capturing.

WHAT IS COMMITTED. Not the versions: four series across their full publication history is about
535 documents and 200,000 observations, most of which repeat the document before them. What is
committed is one row each time a period's value changed, which is the bitemporal table itself
rather than a compression of it.

SOURCE.json IS RECOMPUTED HERE RATHER THAN TRUSTED. It is written by the capture script and
carries the counts this repository quotes, so it is exactly the kind of file that goes stale the
first time somebody re-runs the capture and forgets to look. Every figure in it is derived again
from the CSVs.

THE FOUR PROPERTIES ARE NOT INCIDENTAL. Each one is a way a bitemporal warehouse gets built
wrong, and this data contains all four, which is why these four series were chosen.
"""

from __future__ import annotations

import csv
import json
import pathlib
from collections import defaultdict
from itertools import pairwise
from typing import Any

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
DATA = REPO / "src" / "quarryz" / "data" / "vintages"
COLUMNS = ["period", "value", "released", "version"]
WITHDRAWN = "WITHDRAWN"


def source() -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads((DATA / "SOURCE.json").read_text(encoding="utf-8"))
    return loaded


def series_names() -> list[str]:
    return [str(entry["cdid"]) for entry in source()["series"]]


def rows(cdid: str) -> list[dict[str, str]]:
    with (DATA / f"{cdid}.csv").open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def described(cdid: str) -> dict[str, Any]:
    found: dict[str, Any] = next(entry for entry in source()["series"] if entry["cdid"] == cdid)
    return found


@pytest.mark.parametrize("cdid", series_names())
def test_every_series_has_the_columns_the_loader_expects(cdid: str) -> None:
    """A shifted column puts a release date where a value belongs and nothing reports it."""
    captured = rows(cdid)
    assert captured, f"{cdid}.csv has no rows"
    assert list(captured[0]) == COLUMNS


@pytest.mark.parametrize("cdid", series_names())
def test_the_recorded_counts_are_the_ones_in_the_files(cdid: str) -> None:
    """SOURCE.json is regenerated by the capture, so it is recomputed rather than believed.

    IT SAID THAT BEFORE AND IT WAS TRUE OF FIVE FIELDS OF TWELVE. `versions` in particular, one
    of the numbers this repository quotes and the direct output of the walk-to-404 argument,
    was derived from nothing and could have been set to 9999 with a green suite. A docstring
    promising verification is exactly the assurance that stops a reviewer verifying.
    """
    captured = rows(cdid)
    entry = described(cdid)
    assert entry["changes"] == len(captured)
    assert entry["distinct_release_dates"] == len({row["released"] for row in captured})
    assert entry["withdrawn_rows"] == sum(1 for row in captured if row["value"] == WITHDRAWN)
    assert entry["first_release"] == min(row["released"] for row in captured)
    assert entry["last_release"] == max(row["released"] for row in captured)

    # The version count, bounded by the labels the corpus carries. The CSV holds a row only
    # where a value changed, so a version that published nothing new leaves no label behind and
    # the highest numbered label is a LOWER bound on the walk. Plus one for `current`, which is
    # not numbered. An exact equality would be wrong here and a bound is the honest check.
    numbered = [int(row["version"][1:]) for row in captured if row["version"].startswith("v")]
    assert numbered, f"{cdid} carries no numbered version labels at all"
    assert entry["versions"] >= max(numbered) + 1, (
        f"{cdid} records {entry['versions']} versions and its corpus contains v{max(numbered)}, "
        f"so the recorded count is lower than the labels it holds"
    )
    assert entry["versions"] <= max(numbered) + 5, (
        f"{cdid} records {entry['versions']} versions against a highest label of "
        f"v{max(numbered)}. More than a handful of trailing versions that changed nothing is "
        f"possible and is worth a look rather than a pass"
    )

    # THE FIELD THE WHOLE TIE-BREAK ARGUMENT RESTS ON, and it was recomputed by nothing. Every
    # claim this repository makes about ordering by (released, version) rather than by the date
    # alone depends on there being release dates that carry two versions. If that list were
    # wrong, or stale, the argument would read as strongly as ever and be about nothing.
    # A SUBSET, NOT AN EQUALITY, and getting that wrong is what taught me what the field means.
    # It is computed at capture time over the VERSION WALK: every date on which the publisher
    # issued two versions. The CSV holds a row only where a value changed, so it can only
    # witness a date where BOTH versions changed something. Measured across the four series:
    # DZLS 6 dates walked and 3 witnessed, IKBJ 15 and 2, KAC3 4 and 4, MGRZ 3 and 3. The gap
    # is 18 versions that were published and changed no number at all.
    #
    # The subset direction is the one that can catch a stale file: a date the corpus witnesses
    # and the walk never recorded would mean SOURCE.json describes a different capture.
    versions_per_date: dict[str, set[str]] = defaultdict(set)
    for row in captured:
        versions_per_date[row["released"]].add(row["version"])
    witnessed = sorted(date for date, seen in versions_per_date.items() if len(seen) > 1)
    walked = entry["release_dates_shared_by_two_versions"]
    assert set(witnessed) <= set(walked), (
        f"{cdid} has release dates carrying two versions in the CSV that SOURCE.json does not "
        f"record at all: {sorted(set(witnessed) - set(walked))}. The recorded file describes a "
        f"different capture from the one committed beside it"
    )
    assert walked == sorted(walked), f"{cdid} records the shared dates out of order"
    assert len(set(walked)) == len(walked), f"{cdid} records a shared date twice"

    # `title` and `why` are editorial and cannot be recomputed from a CSV of numbers. They are
    # checked for presence and named here as the two that are not derived, rather than left for
    # a reader to work out which of the twelve fields this test actually stands behind.
    assert entry["title"].strip()
    assert entry["why"].strip()
    assert entry["distinct_titles_over_time"], f"{cdid} records no title at all"
    assert entry["url"].endswith("/data")
    assert cdid.lower() in entry["url"]


def test_a_release_date_is_not_a_unique_key() -> None:
    """TRAP ONE, and the reason transaction time here is a pair rather than a date.

    Two versions published on the same day are two different states of the world. A warehouse
    keyed on the release date alone merges them, and the merge is silent because the second one
    simply overwrites the first.
    """
    # TWO DIFFERENT POPULATIONS, AND THIS TEST FIRST ASSERTED THEY WERE EQUAL. SOURCE.json
    # counts dates shared by two VERSIONS, taken from the walk. The CSV holds a row only where a
    # value CHANGED, so a version that published nothing new leaves no trace in it and its
    # release date can be missing entirely. The right relation is containment, and the claim
    # that matters is that the trap is visible in the committed data at all, not only in the
    # metadata beside it.
    declared: dict[str, list[str]] = {}
    visible: dict[str, list[str]] = {}
    for cdid in series_names():
        by_date: dict[str, set[str]] = defaultdict(set)
        for row in rows(cdid):
            by_date[row["released"]].add(row["version"])
        visible[cdid] = sorted(date for date, versions in by_date.items() if len(versions) > 1)
        declared[cdid] = list(described(cdid)["release_dates_shared_by_two_versions"])
        assert set(visible[cdid]) <= set(declared[cdid]), (
            f"{cdid} shows a shared release date in the data that the capture did not record: "
            f"{sorted(set(visible[cdid]) - set(declared[cdid]))}"
        )

    assert sum(len(dates) for dates in declared.values()) > 0, (
        "no release date in this corpus is shared by two versions, so the pair key this "
        "repository argues for is not motivated by its own data. Find a series where it is, or "
        "drop the claim"
    )
    assert sum(len(dates) for dates in visible.values()) > 0, (
        f"the shared dates exist only in SOURCE.json and never in the committed rows, so a "
        f"reader cannot see the trap in the data: {declared}"
    )


def test_the_pair_of_date_and_version_is_unique() -> None:
    """The other half of trap one: the key this repository does use has to actually be a key."""
    for cdid in series_names():
        seen: set[tuple[str, str, str]] = set()
        for row in rows(cdid):
            key = (row["period"], row["released"], row["version"])
            assert key not in seen, f"{cdid} records {key} twice"
            seen.add(key)


def test_every_version_label_is_well_formed_and_carries_one_release_date() -> None:
    """Added because a mutation renaming a version to v999 passed every other test here.

    The version label is half the transaction-time key, so nothing validating it means half the
    key is unchecked. Three invariants, each of which a corrupted capture would break: the label
    is `v<number>` or `current`, one label never carries two release dates, and the version
    numbering agrees with the publication order.

    The last one is not decoration. If v107 could carry a date before v106's, then "the version
    after this one" and "the version published after this one" would be different orderings, and
    every as-of query would have to say which it meant.
    """
    import re

    for cdid in series_names():
        dates: dict[str, set[str]] = defaultdict(set)
        for row in rows(cdid):
            assert re.fullmatch(r"v\d+|current", row["version"]), (
                f"{cdid} carries a version label of {row['version']!r}"
            )
            dates[row["version"]].add(row["released"])

        for label, released in dates.items():
            assert len(released) == 1, f"{cdid} {label} carries {sorted(released)}"

        numbered = sorted(
            (int(label[1:]), next(iter(released)))
            for label, released in dates.items()
            if label != "current"
        )
        for (earlier, when), (later, then) in pairwise(numbered):
            assert when <= then, (
                f"{cdid} v{earlier} was published {when} and v{later} was published {then}, so "
                f"the version order and the publication order disagree"
            )


def test_a_withdrawn_value_is_kept_as_a_withdrawal() -> None:
    """TRAP THREE. An emptied value is not a null and not an absence.

    The publisher keeps the period and empties the number, so a loader mapping the empty string
    to NULL cannot tell "not published yet" from "withdrawn after publication". Both exist here.
    """
    withdrawn = {cdid: described(cdid)["withdrawn_rows"] for cdid in series_names()}
    assert sum(withdrawn.values()) > 0, (
        f"no series here has a withdrawn value, so trap three is not demonstrated: {withdrawn}"
    )

    # And a withdrawal must be followed by something, or it is indistinguishable from the series
    # simply ending, which is a different event.
    restored = 0
    for cdid in series_names():
        by_period: dict[str, list[str]] = defaultdict(list)
        for row in rows(cdid):
            by_period[row["period"]].append(row["value"])
        for values in by_period.values():
            for earlier, later in pairwise(values):
                if earlier == WITHDRAWN and later != WITHDRAWN:
                    restored += 1
    assert restored > 0, (
        "every withdrawal here is terminal, so nothing distinguishes a withdrawal from the end "
        "of the series and the interesting case is not in the corpus"
    )


def test_a_series_title_changes_without_the_numbers_being_rebased() -> None:
    """TRAP FOUR's cousin, and the one a sibling repository was caught by.

    There, a series was rebased and the title went on claiming the old base for three years. Here
    the opposite happens: titles change while the numbers do not move as a block. A warehouse
    that keys on the title, or that treats a title change as a break in the series, is wrong
    both times.
    """
    changed = {cdid: described(cdid)["distinct_titles_over_time"] for cdid in series_names()}
    assert any(len(titles) > 1 for titles in changed.values()), (
        f"no series here was ever renamed, so this claim has no evidence: {changed}"
    )

    # AND THE SECOND HALF OF THE NAME, which used to be enforced nowhere. This test read one
    # metadata field and asserted nothing about a number, while its own name promises the
    # numbers were not rebased and its docstring cites a sibling repository caught by exactly
    # that. The property is computable from the committed corpus, so it is computed.
    #
    # A rebasing multiplies a whole series by one constant, so the ratio between consecutive
    # vintages is the same for every period. Reconstructed by forward-filling the change table,
    # the median ratio between each pair of consecutive vintages must be exactly 1.
    for cdid in ("KAC3", "MGRZ"):
        vintages: dict[str, dict[str, float]] = {}
        running: dict[str, float] = {}
        for row in sorted(rows(cdid), key=lambda entry: (entry["released"], entry["version"])):
            if row["value"] != WITHDRAWN:
                running[row["period"]] = float(row["value"])
            vintages[f"{row['released']}/{row['version']}"] = dict(running)

        ordered = [vintages[key] for key in sorted(vintages)]
        assert len(ordered) > 50, f"{cdid} reconstructs only {len(ordered)} vintages"
        for earlier, later in pairwise(ordered):
            shared = [
                later[period] / earlier[period]
                for period in earlier
                if period in later and earlier[period] != 0
            ]
            if len(shared) < 10:
                continue
            shared.sort()
            median = shared[len(shared) // 2]
            assert median == 1.0, (
                f"{cdid} has a pair of consecutive vintages whose median ratio is {median}, "
                f"which is what a rebasing looks like. A rescaling read as a revision is the "
                f"trap these four series were chosen to avoid"
            )


def test_the_headline_revision_is_the_largest_in_the_corpus() -> None:
    """THE MAXIMALITY HALF, WHICH WAS ASSERTED IN AN ERROR MESSAGE AND CHECKED BY NOTHING.

    "The largest single revision found anywhere in these four" appears in SOURCE.json, in the
    capture script and in the ledger, and the only test defending it re-checked the arithmetic
    of one hard-coded pair. It could fail if that pair changed and could never fail if some
    other pair became larger, which is the direction that matters: the corpus is regenerated
    against a live publisher, and the next release revising a DZLS or IKBJ annual by more than
    24,521 would make the claim false with a green suite.

    So every adjacent change in every series is measured. Only numeric states count: a
    withdrawal is a revision of a different kind and subtracting it from a number is meaningless.
    """
    largest = (0, "", "", "")
    for cdid in series_names():
        states: dict[str, list[tuple[str, str]]] = defaultdict(list)
        for row in rows(cdid):
            states[row["period"]].append((row["released"], row["value"]))
        for period, sequence in states.items():
            for (_, before), (when, after) in pairwise(sequence):
                if before == WITHDRAWN or after == WITHDRAWN:
                    continue
                size = abs(int(float(after)) - int(float(before)))
                if size > largest[0]:
                    largest = (size, cdid, period, when)

    size, cdid, period, when = largest
    assert (cdid, period) == ("IKBJ", "2021"), (
        f"the largest single revision in this corpus is now {cdid} {period}, {size} at {when}, "
        f"and three files still say it is IKBJ 2021 at 24,521"
    )
    assert size == 24521, f"the largest revision is {size}, and the quoted figure is 24,521"
    assert when == "2023-10-11"


def test_the_headline_revision_is_in_the_data_with_the_numbers_the_readme_quotes() -> None:
    """The one figure a reader will check, recomputed from the file rather than remembered."""
    annual_2021 = [row for row in rows("IKBJ") if row["period"] == "2021"]
    states = [(row["released"], row["value"]) for row in annual_2021]
    assert ("2023-01-13", "-28039") in states
    assert ("2023-10-11", "-3518") in states

    before = next(value for released, value in states if released == "2023-01-13")
    after = next(value for released, value in states if released == "2023-10-11")
    assert int(after) - int(before) == 24521, (
        f"the largest single revision in this corpus is not {int(after) - int(before)}"
    )


def test_the_licence_and_its_attribution_are_recorded_beside_the_data() -> None:
    """The OGL requires a specific sentence, and a licence named without it is not honoured."""
    licence = source()
    assert licence["licence"] == "Open Government Licence v3.0"
    assert licence["attribution"] == (
        "Contains public sector information licensed under the Open Government Licence v3.0."
    )
    assert "adapt the Information" in licence["permits_adaptation"]


def test_none_of_these_series_belongs_to_the_sibling_that_also_reads_ons() -> None:
    """Two repositories in one portfolio reading the same four series would be one repository.

    Named here rather than remembered, because the overlap is invisible from inside either one.
    """
    theirs = {"IHYQ", "MGSX", "ABMI", "D7BT"}
    assert not theirs & set(series_names())
